service: my-serverless-app

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements: ${file(./iam.yml)}
  # iam:
  #   role:
  #     statements:
  #       - Effect: Allow
  #         Action: lambda:InvokeFunction
  #         Resource: arn:aws:lambda:us-east-1:324425813232:function:my-serverless-app-dev-lambdaTwo

functions:
  lambdaOne:
    handler: lambdaOne.handler
    events:
      - http:
          path: /iterable/{proxy+}
          method: get
          cors: true
      - http:
          path: /iterable/{proxy+}
          method: post
          cors: true
  lambdaTwo:
    handler: lambdaTwo.handler
